import Head from "next/head";
import Button from "@mui/material/Button";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by Level4" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>hello world</h1>

        <Button variant="contained">Hello World</Button>
      </main>

      <footer></footer>
    </div>
  );
}
